name: Run Selenium Tests at 2 AM (Monday to Friday)

on:
  schedule:
    # This cron expression runs the workflow at 2 AM every Monday to Friday
    - cron: '30 20 * * 1-5'

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK (if you're using Python for Selenium tests)
        uses: actions/setup-python@v2
        with:
          java-version: '11'  # Replace with your required version

      - name: Install Dependencies
        run: mvn install

      - name: Run Selenium Tests
        run: mvn test  # Or whatever command you use to run your tests

      - name: Upload Test Results (optional)
        uses: actions/upload-artifact@v2
        with:
          name: selenium-test-results
          path: D:/Eclipse_Workspace/AN4_Parallel_Testing_Local/extent-test-output  # Path to your test result reports
